
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'HTClassScrollViewCustomLayout_Example' do
  pod 'HTClassScrollViewCustomLayout', :path => '../'

  target 'HTClassScrollViewCustomLayout_Tests' do
    inherit! :search_paths

    
  end
end
